# Generated by Django 4.0.8 on 2023-10-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_payment_delete_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='department',
            field=models.CharField(default='Some Default Department', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
