# Generated by Django 4.0.8 on 2023-10-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_payment_comments_payment_department_payment_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='student_ID',
            field=models.CharField(default='301', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='department',
            field=models.CharField(default='CSE', max_length=50),
        ),
    ]
