# Generated by Django 4.0.8 on 2023-10-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_payment_student_id_alter_payment_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='department',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student_ID',
            field=models.CharField(default='', max_length=50),
        ),
    ]
