# Generated by Django 4.0.8 on 2023-10-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_attendance_class_attended_attendance_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='course',
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
