# Generated by Django 4.0.8 on 2023-10-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_attendance_course_attendance_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
